# Generated by Django 5.2.4 on 2025-08-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="preference",
            field=models.JSONField(blank=True),
        ),
    ]
