# Generated by Django 5.2.4 on 2025-08-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0005_alter_userprofile_preference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="preference",
            field=models.TextField(blank=True),
        ),
    ]
