# Generated by Django 5.2.4 on 2025-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0008_moodentry_habitcompletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodentry",
            name="score",
            field=models.IntegerField(
                choices=[
                    (1, "😢 Sad"),
                    (2, "😐 Meh"),
                    (3, "😊 Happy"),
                    (4, "😡 Angry"),
                    (5, "😴 Tired"),
                ]
            ),
        ),
    ]
