# Generated by Django 5.2.5 on 2025-08-07 18:22

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0009_alter_moodentry_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region="ZA"
            ),
        ),
    ]
