# Generated by Django 5.2.5 on 2025-08-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0011_address_userprofile_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habitcompletion",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="moodentry",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterField(
            model_name="moodentry",
            name="score",
            field=models.IntegerField(
                choices=[
                    (1, "1 😢 Sad"),
                    (2, "2 😐 Meh"),
                    (3, "3 😊 Happy"),
                    (4, "4 😡 Angry"),
                    (5, "5 😴 Tired"),
                ]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="moodentry",
            unique_together={("user", "date")},
        ),
    ]
