# Generated by Django 5.2.5 on 2025-08-25 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0012_alter_habitcompletion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="low_mood_threshold",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="notify_low_mood",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="reminder_hour_local",
            field=models.PositiveSmallIntegerField(default=9),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="UTC", max_length=64),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="profiles",
                to="tracker.address",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="preference",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read", models.BooleanField(default=False)),
                ("category", models.CharField(default="info", max_length=32)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HabitReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("next_trigger_utc", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="tracker.habit",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_trigger_utc"],
                "unique_together": {("user", "habit")},
            },
        ),
    ]
