# Generated by Django 5.2.5 on 2025-08-25 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0013_userprofile_low_mood_threshold_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="preference",
        ),
    ]
