# Generated by Django 5.2.5 on 2025-08-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0014_remove_userprofile_preference"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calendar_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
    ]
