# Generated by Django 5.2.5 on 2025-08-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0015_user_calendar_token_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodentry",
            name="score",
            field=models.IntegerField(
                choices=[
                    (1, "1 😡 Angry"),
                    (2, "2 😴 Tired"),
                    (3, "3 😢 Sad"),
                    (4, "4 😐 Meh"),
                    (5, "5 😊 Happy"),
                ]
            ),
        ),
    ]
