# Generated by Django 5.2.5 on 2025-08-28 19:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0016_alter_moodentry_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodentry",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
