# Generated by Django 5.2.5 on 2025-09-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0017_alter_moodentry_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitcompletion",
            name="date",
            field=models.DateField(),
        ),
    ]
