# Generated by Django 5.2.5 on 2025-09-26 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0018_alter_habitcompletion_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitcompletion",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
